---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Arrow.
--- DateTime: 2020/2/1 16:45
---
---
-- 删除选课信息
local temp_set = "tset"
redis.call("sadd",temp_set,argv[1]) --给temp_set添加当前要删除的课程id
if redis.call("sismember",keys[1],argv[1])==true   -- 判断当前用户的选课集合里时候有带删除的课程id
then redis.call("sdiffstore",keys[1],keys[1],temp_set)
else return 0
end

--增加库存
store = tonumber(redis.call("hget",argv[1],argv[2])) --获取库存
store = store + 1 --更新库存
redis.call("hset",argv[1],argv[2],store) --保存库存
return 1
